### PR TITLE
Bug 1469617 - upgrade to use rootUrl

### PR DESCRIPTION
**Pull request by djmitche**
The commits are nice to look at one-by-one.  Basically, this updates a bunch of libraries.

For rootUrl, it reads rootUrl from `config.yml` if given, which gets it from `TASKCLUSTER_ROOT_URL` if given as part of userData, it uses that, otherwise asumes https://taskcluster.net.

The tests all assume that they will be given TASKCLUSTER_ROOT_URL.

I don't have a great way to test this, since the docker-worker-test image is missing.  A few of the mocha test scripts run OK, so that's something.  This is admittedly a huge change to make without testing, so one that's fixed I'll revisit testing it out.

### CODE REVIEW

**Comment by walac** [comment]
Depends on #411

**Comment by djmitche** [comment]
Ok, let's see how that does!  Most of the tests pass for me, but for some reason deviceCapacity = 0 on my host so the tests that require running the worker in a container don't pass.  If they pass for the PR I'll call it good, though..

**Comment by djmitche** [comment]
Hm, [this run](https://tools.taskcluster.net/groups/V3G0Z9XiRt65044_s5O8JQ) was successful, but after I squashed a stray commit two runs failed :(

**Comment by djmitche** [comment]
Hah, and as usual with docker-worker, I don't know how that run was green.  It had a bug (not renaming `project` to `projectName`) which should have caused that test suite to fail every time.

**Comment by djmitche** [comment]
OK, looks like this time through it was just a normal Docker failure:

```
     Error: (HTTP code 500) server error - Unable to remove filesystem for 7cf8c124f00d86181e2bc0b9a34d31693f7f0682f3fcb32db19ed056a7350a5d: remove /var/lib/docker/containers/7cf8c124f00d86181e2bc0b9a34d31693f7f0682f3fcb32db19ed056a7350a5d/shm: device or resource busy 
```

so i suspect all of the rootUrl-related issues are worked out here.

**Comment by walac** [comment]
I ran the failed chunk locally, and the tests fail with a repeated pattern:

```js
Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:129:11)
    at Object.request (http.js:39:10)
    at Object.request (https.js:239:15)
    at Request.request (/worker/node_modules/superagent/lib/node/index.js:622:31)
    at Request.end (/worker/node_modules/superagent/lib/node/index.js:764:8)
    at Request._redirect (/worker/node_modules/superagent/lib/node/index.js:467:8)
    at ClientRequest.req.once.res (/worker/node_modules/superagent/lib/node/index.js:832:19)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
```

**Comment by djmitche** [comment]
Hm, and the scope errors are still present, despite having the scope:
```
[taskcluster:error] Docker configuration could not be created.  This may indicate an authentication error when validating scopes necessary for running the task. 
 Error: Insufficient scopes to attach cache volumes.  The task must have scope `docker-worker:cache:<cache-name>` for each cache in `payload.caches`.
[taskcluster 2018-09-20 11:31:15.091Z] Unsuccessful task run with exit code: -1 completed in 0.914 seconds
```
This intermittency thing is killing me :(

**Comment by djmitche** [comment]
Oh, it's just a different required scope, wtf

**Comment by djmitche** [comment]
checks

DON'T TOUCH IT!

**Pull request merged**
