### PR TITLE
add better logging for coalescing, use routePrefix

### PR DESCRIPTION
**Pull request by djmitche**
Hopefully this will tell me why, when things are not coalesced.

### CODE REVIEW

**Comment by djmitche** [comment]
OK, this seems to be working in ami-test right now.

**Comment by gregarndt** [comment]
Looks good to me and looking at the tests it didn't break anything that wasn't broken before.

**Comment by gregarndt** [comment]
Let me know what button pushing you would like.  I can merge and deploy it wherever you want.

**Comment by djmitche** [comment]
Do you want to get it merged and amis generated?  I expect my tree is not up to date with master, so the AMIs I generated are probably not good to deploy.

Once that's in place, shoot me the ami IDs in email and I can start plugging them into the appropriate workerTypes one at a time.

**Pull request merged**
