### PR TITLE
bug 1534506 - Remove cot openpgp usage.

### PR DESCRIPTION
**Pull request by escapewindow**
I believe we still use openpgp for encrypted env vars, so I left that in place. I just removed any cot gpg references.

This can roll out at any time. If this lands before we rotate the gpg keypair, we can just get rid of the gpg keypair.

### CODE REVIEW

**Comment by escapewindow** [comment]
@walac putting this on your radar. No rush, though the sooner we land this, the sooner we can ditch the cot openpgp keypair.

**Comment by escapewindow** [comment]
> There are more places to change:
> 
>     * Remove the [script](https://github.com/taskcluster/docker-worker/blob/master/deploy/bin/gen-signing-key) to create the keys
> 
>     * Remove it from [deployment scripts](https://github.com/taskcluster/docker-worker/blob/master/deploy/packer/app.json#L60-L79)

Are we sure this isn't the encrypted env vars key?

> Also, you need to rebase your branch to get tests green.

Done.

**Comment by escapewindow** [comment]
Removed the signingKeyLocation and gen-signing-key refs.

**Comment by walac** [comment]
Some more places: [here](https://github.com/taskcluster/docker-worker/blob/master/deploy/bin/import-docker-worker-secrets#L52-L53), [here](https://github.com/taskcluster/docker-worker/blob/master/deploy/bin/import-docker-worker-secrets#L66), [here](https://github.com/taskcluster/docker-worker/blob/master/deploy/packer/app.json#L60-L65), [here](https://github.com/taskcluster/docker-worker/blob/master/deploy/packer/app.json#L72-L75), [here](https://github.com/taskcluster/docker-worker/blob/master/deploy/template/packer/app.json#L3) and [here](https://github.com/taskcluster/docker-worker/blob/master/deploy/variables.js#L51-L53).

I am quite sure I am missing a spot, but I handle it if there one.

**Comment by escapewindow** [comment]
Done, and just now fixed the recent merge conflicts.

**Comment by escapewindow** [comment]
Looks like we need a `let verified = Buffer.from(chainOfTrust);` or something? Not sure if we can reuse the buffer like that, or if we need to write it to disk or what.

**Comment by walac** [comment]
> Looks like we need a let verified = Buffer.from(chainOfTrust); or something? Not sure if we can reuse the buffer like that, or if we need to write it to disk or what.

I think we can't, the `Buffer.from` value must be saved in a variable.

**Comment by escapewindow** [comment]
This may have fixed it. My local tests in vagrant are timing out :\

**Comment by escapewindow** [comment]
@walac do you know if you want these changes? If so, we can keep working on this PR. If not, we can leave this until generic-worker replaces docker-worker. (That means we'll still create gpg-signed cot artifacts in docker-worker, even though they're obsolete.)

**Comment by walac** [comment]
@escapewindow Oh, sorry, I am so much with heads down with other stuff that I forgot your PR. Yes, definitely this is worth. I will re-review it soon. I am so sorry again.

**Comment by escapewindow** [comment]
Thanks!

**Pull request merged**
