### PR TITLE
Bug 1455117 - check supersederUrl before fetching it

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by walac** [comment]
It feels like it broke a bunch of tests. Chunk 1 seems suspicious, I retriggered it.

**Comment by djmitche** [comment]
Looks like it was a regex-quoting issue.  I've pushed a new change.

**Comment by djmitche** [comment]
Third time is the charm?

**Comment by djmitche** [comment]
Yup, that single error looks unrelated.

**Pull request merged**
