### PR TITLE
Bug 1553953 - use a valid workerType for tests

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
Those all failed with

https://tools.taskcluster.net/groups/HhDaRBgERhuGHQ0xdk4mjQ/tasks/AKvQwvMFTveXhYO6eSTN1A/runs/0/logs/public%2Flogs%2Flive.log
```
[taskcluster:error] Docker configuration could not be created.  This may indicate an authentication error when validating scopes necessary for running the task. 
 Error: Unknown Server Error
```

**Comment by walac** [comment]
If it fails on the next round of tests, let it so that I will check what's wrong.

**Comment by jdm** [comment]
This is the same error that all of Servo's docker-worker-based taskcluster jobs have been reporting since yesterday afternoon.

**Comment by walac** [comment]
It feels like there are some tests failing.

**Comment by djmitche** [comment]
I'll look

**Comment by djmitche** [comment]
Silly typo.. let's see if this fixes it.

**Comment by djmitche** [comment]
All Green :D

**Pull request merged**
