### PR TITLE
Bug 1491022 - Upgrade to docker-exec-websocket-server with newer lodash

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by walac** [comment]
Depends on #411

**Comment by djmitche** [comment]
Rebased .. let's see how the tests turn out..

**Comment by djmitche** [comment]
green :D

**Comment by djmitche** [comment]
@walac did this get deployed?  It looks like the last release was July 26?

**Comment by walac** [comment]
Nope, I am going to do it

**Pull request merged**
