### PR TITLE
Bug 1604175 - allow longer maxRunTime (up to 1 week)

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by walac** [comment]
@djmitche For some reason you were unlucky enough to get a bug in tests triggered by your patch. This fixes it:
```
vagrant@ubuntu-14:/vagrant$ git diff
diff --git a/test/integration/docker_manifest_test.js b/test/integration/docker_manifest_test.js
index 3be6741..f693afc 100644
--- a/test/integration/docker_manifest_test.js
+++ b/test/integration/docker_manifest_test.js
@@ -10,7 +10,7 @@ const debug = require('debug')('docker-worker:test:docker-manifest');

 suite('docker image with manifest.json file', function() {
   test('docker manifest', async () => {
-    let worker = new TestWorker(DockerWorker);
+    let worker = new TestWorker(DockerWorker, 'docker-worker', 'docker-worker');
     await worker.launch();

     const imageTaskId = slugid.v4();
```

**Comment by djmitche** [comment]
pushed..

**Comment by marco-c** [comment]
@walac ping

**Comment by marco-c** [comment]
How do deployments of docker-worker work? Once this is merged, will it be deployed right away?

@walac since the test failures are unrelated to the PR, could it be merged as-is and the test failures dealt with in separate PRs?

**Comment by marco-c** [comment]
@walac could you deploy this change?

**Pull request merged**
