### PR TITLE
Bug 1375190 - Retrieve AWS worker secrets from taskcluster secrets service

### PR DESCRIPTION
**Pull request by petemoore**
Hi guys,

This is my first stab at retrieving AWS worker secrets from taskcluster-secrets service rather than from the provisioner secrets method (via the `data` property).

I expect it to take a few iterations for me to get this right, due to my limited experience writing javascript, so I'll only flag for review once I have the CI passing and I'm confident it is ready.

Creating the PR now to make it easier to navigate CI results while developing...

See [bug 1375190](https://bugzil.la/1375190) for context.

### CODE REVIEW

**Comment by petemoore** [comment]
I don't think there are any existing tests that fetch secrets from the provisioner, otherwise they would fail with this change to fetch them from taskcluster secrets service instead. So @walac please let me know if there is an easy way to test this change before we land it. Is this something we can do with `ami-test`/`ami-test-pv` worker type(s)?

**Comment by walac** [comment]
you can run `./deploy.sh --test` to build and deploy it on ami-test. Look at [README](https://github.com/taskcluster/docker-worker/blob/master/README.md) and [FAQ](https://github.com/taskcluster/docker-worker/blob/master/FAQ.md) files for details.

**Comment by petemoore** [comment]
> you can run `./deploy.sh --test` to build and deploy it on ami-test. Look at [README](https://github.com/taskcluster/docker-worker/blob/master/README.md) and [FAQ](https://github.com/taskcluster/docker-worker/blob/master/FAQ.md) files for details.

Thanks Wander! I'm currently deploying to `ami-test` and will post back results.

**Comment by petemoore** [comment]
> > you can run `./deploy.sh --test` to build and deploy it on ami-test. Look at [README](https://github.com/taskcluster/docker-worker/blob/master/README.md) and [FAQ](https://github.com/taskcluster/docker-worker/blob/master/FAQ.md) files for details.
> 
> Thanks Wander! I'm currently deploying to `ami-test` and will post back results.

Deployment was successful. I made sure there were no running workers, deleted secrets from the ami-test worker type definition (to ensure that the new feature is working) and have created task [SjbDgpY4QfK9ScbTM4aTZg](https://tools.taskcluster.net/groups/SjbDgpY4QfK9ScbTM4aTZg/tasks/SjbDgpY4QfK9ScbTM4aTZg/details) to test that the worker can run a task. Moreover, this task logs slowly to standard out, which will give us a change to check that livelog is working. This is useful, since some of the config settings which were moved from the `secrets` property of the worker type definition are required for live logs. So if the logs stream ok, that means the worker must have retrieved the secret config from the secrets service. Let's wait and see!

**Comment by petemoore** [comment]
The worker didn't crash, and ran the task, but the livelogs didn't work.

The [papertrail logs](https://papertrailapp.com/systems/2977157331/events?focus=1032393712895950850&selected=1032393712895950850) reported no problems:

```
{"type":"read userdata","source":"host/aws","text":{"availabilityZone":"us-east-1b","capacity":1,"data":{"capacityManagement":{"diskspaceThreshold":30000000000}},"instanceType":"m5d.4xlarge","lastModified":"2019-02-13T17:24:55.802Z","launchSpecGenerated":"2019-02-13T17:29:08.988Z","price":0.2769,"provisionerBaseUrl":"https://aws-provisioner.taskcluster.net/v1","provisionerId":"aws-provisioner-v1","region":"us-east-1","securityToken":"**********************","spotBid":4,"taskclusterRootUrl":"https://taskcluster.net","workerType":"ami-test"}}
{"type":"read secrets","source":"host/aws"}
{"type":"config","source":"host/aws","host":"ec2-35-168-32-101.compute-1.amazonaws.com","publicIp":"35.168.32.101","privateIp":"172.31.69.102","workerId":"i-0f64b5d7ba5cf0aab","workerGroup":"us-east-1","workerNodeType":"m5d.4xlarge","instanceId":"i-0f64b5d7ba5cf0aab","region":"us-east-1b","instanceType":"m5d.4xlarge","shutdown":{"enabled":true,"afterIdleSeconds":900}}
{"type":"handle shutdowns","source":"top","provisionerId":"aws-provisioner-v1","workerId":"i-0f64b5d7ba5cf0aab","workerGroup":"us-east-1","workerType":"ami-test","workerNodeType":"m5d.4xlarge"} 
```

**Comment by petemoore** [comment]
With extra logging, I found the problem! I had forgotten that the blob returned from tcsecrets.get(<secretName>) isn't the secret itself, but is {"secret": <secret>, "expires": <expiry>}.

So I need to merge in `workerTypeSecret.secret`, not `workerTypeSecret`. I've force pushed a fix, and am redeploying to `ami-test` worker type to try it out again.

**Comment by petemoore** [comment]
Live logs working! \o/

https://tools.taskcluster.net/groups/SjbDgpY4QfK9ScbTM4aTZg/tasks/E7ggXxODRvSZuLVQZFzcag/runs/0/logs/public%2Flogs%2Flive.log

@walac This is now ready for review.

**Comment by petemoore** [comment]
Linux64 test build on `ami-test`:

https://tools.taskcluster.net/groups/ZSLswW7pSwiybCRFtZ0v8g/tasks/ZSLswW7pSwiybCRFtZ0v8g/runs/0/logs/public%2Flogs%2Flive.log

**Pull request merged**
